#!/bin/bash

screenshot_directory="/home/sayed/Pictures/Screenshots"

latest_screenshot=$(ls -t "$screenshot_directory"/*.png | head -n 1)

if [ -z "${latest_screenshot}" ]; then
  echo "No screenshots found"
  exit 1
fi

extract_text=$(tesseract "$latest_screenshot" stdout 2>/dev/null)

if [ "${extract_text}" ]; then
  echo "${extract_text}" | xclip -selection clipboard
else
  echo "tesseract not found: sudo apt-get install tesseract-ocr-spa"
fi
