#!/bin/bash

values=$(cat "/home/sayed/paths.txt")
echo "${values[@]}"

selected_value=$(echo -e "${values[@]}" | rofi -dmenu -p "ADD/RM/SELECT ")

if [[ "$selected_value" == "ADD" ]]; then
  result=$(rofi -dmenu -p "Enter something")
  echo "You entered: ${result}"
  echo "$result" >>"/home/sayed/paths.txt"
elif [[ "$selected_value" == "RM" ]]; then
  nano /home/sayed/paths.txt
elif [[ -n $selected_value ]]; then
  code "$selected_value"
fi
