#!/bin/bash

cmdlist=~/.cmdlist
exe=/tmp/tempcmd

if [ $# == 0 ]; then
  echo "Usage: cmd <command>"
  echo -e "\nYour Commands : "
  cat "${cmdlist}"
  exit 1
fi

key=$1
line=$(grep -m 1 "^${key}=" "${cmdlist}")

if [ -z "${line}" ]; then
  echo "Command isn't existed, choose one of below:"
  cat ${cmdlist}
else
  echo "${line}"
  cmd=$(echo "${line}" | cut -d "=" -f 2)
  echo "${cmd}" >"${exe}"
  bash "${exe}"
fi
