#!/bin/bash

systemPath="/etc/systemd/system/"

# Check for root privileges
if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root (use sudo)"
  exit 1
fi

read -r -p "Enter the service path: " servicePath
read -r -p "Enter Service Name (No Spaces): " serviceName
read -r -p "Enter the fullpath of the executable: " execStart
read -r -p "Does the service need GUI (y/n)? " wantedGUI

if [ "${wantedGUI}" == "y" ]; then
  TARGET="graphical.target"
  ENV="Environment=DISPLAY=:0"
  AFTER="After=graphical.target"
else
  TARGET="multi-user.target"
  ENV=""
  AFTER="After=network.target"
fi

cat <<EOF >"${servicePath}/${serviceName}.service"
[Unit]
Description=${serviceName}
${AFTER}

[Service]
ExecStart=${execStart}
$ENV

[Install]
WantedBy=${TARGET}
EOF

echo "File created locally at ${servicePath}/${serviceName}.service"

echo "Linking to systemd..."
cp "${servicePath}/${serviceName}.service" "${systemPath}/${serviceName}.service"
sudo systemctl daemon-reload

echo "Done, service is linked to systemd and ready to use!"
echo "To start the service use this command ==> sudo systemctl enable ${serviceName}.service"
